// eslint-disable-next-line
export const ACTIONS = {
  GET_PROJECTS: 'GET_PROJECTS',
  NEW_PROJECT: 'NEW_PROJECT',
  NEW_TASK: 'NEW_TASK',
  EDIT_TASK: 'EDIT_TASK',
  REMOVE_TASK: 'REMOVE_TASK',
  DELETE_PROJECT: 'DELETE_PROJECT'
};
